import { BookOpen, Check, Clipboard, Database, FileText, History, MapPin } from 'lucide-react'
import { useState } from 'react'
import { api, isMissingRoute, listFrom } from '../api/client'
import { useResource } from '../api/useResource'
import { AsyncState, Badge, EmptyResults, PageHeader, Panel, SearchInput, Select } from '../components/ui'
import type { Clause, Contract } from '../types/domain'

const EMPTY_CLAUSES: Clause[] = []
const EMPTY_CONTRACTS: Contract[] = []

function Highlight({ text, match }: { text: string; match?: string }) { if (!match) return <>{text}</>; const index = text.toLowerCase().indexOf(match.toLowerCase()); return index < 0 ? <>{text}</> : <>{text.slice(0, index)}<mark>{text.slice(index, index + match.length)}</mark>{text.slice(index + match.length)}</> }
function flattenClause(item: Clause | { clause?: Clause; score?: number }) { return 'clause' in item && item.clause ? { ...item.clause, score: item.score } : item as Clause }

export function ClauseSearchPage() {
  const [query, setQuery] = useState(''); const [contractId, setContractId] = useState('All contracts'); const [status, setStatus] = useState('All'); const [tier, setTier] = useState('All'); const [selectedId, setSelectedId] = useState(''); const [copied, setCopied] = useState(false)
  const contractsResource = useResource((signal) => api.get<unknown>('/contracts?page=1&pageSize=100', signal).then(p => listFrom<Contract>(p, 'contracts')), [])
  const clausesResource = useResource(async (signal) => {
    let payload: unknown
    if (query.trim()) {
      try { payload = await api.post<unknown>('/clause-search', { query: query.trim(), mode: 'AND', contractId: contractId === 'All contracts' ? null : contractId, status: status === 'All' ? null : status, tier: tier === 'All' ? null : tier, page: 1, pageSize: 100 }, signal) }
      catch (error) { if (!isMissingRoute(error)) throw error; const params = new URLSearchParams({ q: query.trim(), mode: 'AND', page: '1', pageSize: '100' }); if (contractId !== 'All contracts') params.set('contractId', contractId); if (status !== 'All') params.set('status', status); if (tier !== 'All') params.set('tier', tier); payload = await api.get<unknown>(`/clauses/search?${params}`, signal) }
    } else payload = await api.get<unknown>('/clauses?page=1&pageSize=100', signal)
    return listFrom<Clause | { clause?: Clause; score?: number }>(payload, 'clauses', 'matches').map(flattenClause).filter(clause => (contractId === 'All contracts' || clause.contractId === contractId) && (status === 'All' || clause.status === status) && (tier === 'All' || clause.tier === tier))
  }, [query, contractId, status, tier])
  const clauses = clausesResource.data ?? EMPTY_CLAUSES; const contracts = contractsResource.data ?? EMPTY_CONTRACTS; const selected = clauses.find(c => c.id === selectedId) ?? clauses[0]; const contract = contracts.find(c => c.id === selected?.contractId)
  const reset = () => { setQuery(''); setContractId('All contracts'); setStatus('All'); setTier('All'); setSelectedId('') }
  const copy = async () => { if (!selected) return; try { await navigator.clipboard.writeText(selected.text); setCopied(true); window.setTimeout(() => setCopied(false), 1600) } catch { setCopied(false) } }
  return <><PageHeader title="Clause search" description="Find approved language and verify every result against its contract source." /><div className="search-hero"><SearchInput value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search wording, clause title, or tag" aria-label="Search indexed clauses" /><span>{clauses.length} results</span></div><div className="filter-row"><Select label="Contract" value={contractId} onChange={(e) => setContractId(e.target.value)}><option>All contracts</option>{contracts.map(c => <option key={c.id} value={c.id}>{c.id}</option>)}</Select><Select label="Position" value={tier} onChange={(e) => setTier(e.target.value)}><option>All</option><option>Preferred</option><option>Acceptable</option><option>Fallback</option><option>Restricted</option></Select><Select label="Status" value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option><option>Compliant</option><option>Needs Review</option><option>Exception</option></Select></div>
    <AsyncState loading={clausesResource.loading || contractsResource.loading} error={clausesResource.error ?? contractsResource.error} onRetry={() => { clausesResource.retry(); contractsResource.retry() }}><div className="search-layout"><div><div className="results-meta"><strong>{clauses.length} indexed clauses</strong><span>Results computed by the local inverted index</span></div>{clauses.length ? <div className="search-results">{clauses.map(clause => <button key={`${clause.contractId}-${clause.id}`} className={selected?.id === clause.id ? 'selected' : ''} onClick={() => { setSelectedId(clause.id); setCopied(false) }}><div className="result-head"><span><FileText size={16} />{contracts.find(c => c.id === clause.contractId)?.name ?? clause.contractId}</span><span className={`position-label position-${clause.tier?.toLowerCase()}`}>{clause.tier}</span></div><h2>{clause.id} / {clause.title}</h2><p><Highlight text={clause.matchedText ?? clause.text} match={query || clause.match} /></p><footer><span><MapPin size={12} />Page {clause.pageNumber}</span><span>{clause.version}</span><Badge>{clause.status}</Badge></footer></button>)}</div> : <EmptyResults onReset={reset} />}</div>
      <aside className="preview-column"><Panel className="index-card"><Database /><div><span>Search method</span><h2>Inverted index</h2><p>Unicode-normalized term postings</p></div><Badge tone="compliant">Live</Badge></Panel>{selected ? <Panel className="clause-preview"><div className="preview-head"><span>Evidence record</span></div><div className="evidence-source"><BookOpen size={19} /><div><strong>{contract?.name ?? selected.contractId}</strong><span>{selected.sourceSection}</span></div><span>p. {selected.pageNumber}</span></div><div className="clause-title-line"><div><h2>{selected.title}</h2><p className="preview-id">{selected.id} / {selected.version}</p></div><span className={`position-label position-${selected.tier?.toLowerCase()}`}>{selected.tier}</span></div><blockquote>{selected.text}</blockquote><button className="copy-clause" onClick={copy}>{copied ? <Check size={15} /> : <Clipboard size={15} />}{copied ? 'Copied' : 'Copy clause text'}</button><div className="guidance-note"><strong>Review guidance</strong><p>{selected.guidance || 'Verify this wording against the governing obligation before approval.'}</p></div><div className="evidence-history"><History size={15} /><span>Current {selected.version}{selected.previousVersion ? ` / previous ${selected.previousVersion}` : ''}</span></div><div className="tag-row">{selected.tags?.map(tag => <span key={tag}>{tag}</span>)}</div></Panel> : <Panel className="clause-preview"><p className="muted">Adjust the filters to view an evidence record.</p></Panel>}</aside></div></AsyncState></>
}
