import { ListFilter, Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router'
import { api, listFrom } from '../api/client'
import { useResource } from '../api/useResource'
import { AsyncState, Badge, Button, EmptyResults, PageHeader, Panel, SearchInput, Select } from '../components/ui'
import type { Contract } from '../types/domain'

const EMPTY_CONTRACTS: Contract[] = []

export function ContractsPage() {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const [department, setDepartment] = useState('All'); const [sort, setSort] = useState('Recently modified')
  const resource = useResource((signal) => api.get<unknown>('/contracts?page=1&pageSize=100', signal).then((payload) => listFrom<Contract>(payload, 'contracts')), [])
  const contracts = resource.data ?? EMPTY_CONTRACTS
  const results = useMemo(() => contracts.filter((contract) => `${contract.name}${contract.id}${contract.type}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || contract.compliance === status) && (department === 'All' || contract.department === department)).sort((left, right) => sort === 'Name' ? left.name.localeCompare(right.name) : sort === 'Risk' ? ({ High: 0, Medium: 1, Low: 2 }[left.risk] - { High: 0, Medium: 1, Low: 2 }[right.risk]) : right.lastModified.localeCompare(left.lastModified)), [contracts, query, status, department, sort])
  const reset = () => { setQuery(''); setStatus('All'); setDepartment('All'); setSort('Recently modified') }
  return <><PageHeader title="Contracts" description="Browse the Contract Corpus and track current versions, ownership, and review status." actions={<Button disabled title="Contract creation is not exposed by this API"><Plus size={16} /> Add contract</Button>} /><AsyncState loading={resource.loading} error={resource.error} empty={!contracts.length} onRetry={resource.retry}><Panel className="table-panel"><div className="filter-bar"><SearchInput value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search contracts or IDs..." aria-label="Search contracts" /><Select label="Compliance" value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option><option>Compliant</option><option>Needs Review</option><option>Exception</option></Select><Select label="Department" value={department} onChange={(e) => setDepartment(e.target.value)}><option>All</option>{[...new Set(contracts.map((c) => c.department))].map((d) => <option key={d}>{d}</option>)}</Select><Select label="Sort by" value={sort} onChange={e => setSort(e.target.value)}><option>Recently modified</option><option>Name</option><option>Risk</option></Select><button className="filter-summary"><ListFilter size={16} />{results.length} of {contracts.length}</button></div>{results.length ? <div className="table-scroll"><table className="contracts-table"><thead><tr><th>Contract</th><th>Type</th><th>Current version</th><th>Last modified</th><th>Owner</th><th>Compliance</th><th>Review status</th></tr></thead><tbody>{results.map((contract) => <tr key={contract.id}><td><Link className="contract-link" to={`/contracts/${contract.id}`}><strong>{contract.name}</strong><span>{contract.id}</span></Link></td><td>{contract.type}</td><td><span className="version-pill">{contract.currentVersion}</span></td><td>{contract.lastModified}</td><td><div className="owner-cell"><span>{contract.owner.split(' ').map((s) => s[0]).join('')}</span>{contract.owner}</div></td><td><Badge>{contract.compliance}</Badge></td><td><Badge>{contract.reviewStatus}</Badge></td></tr>)}</tbody></table></div> : <EmptyResults onReset={reset} />}<div className="table-footer"><span>Showing {results.length} contracts</span><div><button disabled>Previous</button><button className="current">1</button><button disabled>Next</button></div></div></Panel></AsyncState></>
}
