import { ArrowRight, ArrowUpRight, FileText, GitCompareArrows, Search, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router'
import { api, listFrom } from '../api/client'
import { useResource } from '../api/useResource'
import { AsyncState, Badge, PageHeader } from '../components/ui'
import type { Contract, DashboardSummary, ReviewItem, Reviewer } from '../types/domain'

interface OverviewData { summary: Partial<DashboardSummary>; contracts: Contract[]; reviews: ReviewItem[]; reviewers: Reviewer[] }

export function OverviewPage() {
  const [filter, setFilter] = useState('Open')
  const resource = useResource<OverviewData>(async (signal) => {
    const [summary, contractsPayload, reviewsPayload, reviewersPayload] = await Promise.all([
      api.get<Partial<DashboardSummary>>('/dashboard/summary', signal), api.get<unknown>('/contracts?page=1&pageSize=100', signal), api.get<unknown>('/reviews?page=1&pageSize=8', signal), api.get<unknown>('/reviewers?page=1&pageSize=6', signal),
    ])
    return { summary, contracts: listFrom<Contract>(contractsPayload, 'contracts'), reviews: listFrom<ReviewItem>(reviewsPayload, 'reviews'), reviewers: listFrom<Reviewer>(reviewersPayload, 'reviewers') }
  }, [])
  const data = resource.data
  const contracts = data?.contracts ?? data?.summary.recentContracts ?? []
  const reviews = data?.reviews ?? data?.summary.reviewQueue ?? []
  const reviewers = data?.reviewers ?? []
  const tasks = reviews.filter((item) => filter === 'All' || (filter === 'Urgent' ? item.priority === 'Urgent' : item.status !== 'Completed'))
  const counts = { compliant: contracts.filter((c) => c.compliance === 'Compliant').length, review: contracts.filter((c) => c.compliance === 'Needs Review').length, exception: contracts.filter((c) => c.compliance === 'Exception').length }
  return <div className="workbench"><PageHeader title="Overview" description="Your contracts, decisions, and next steps." actions={<Link className="button button-primary" to="/contracts">Open contract register <ArrowUpRight size={16} /></Link>} />
    <AsyncState loading={resource.loading} error={resource.error} empty={!contracts.length && !reviews.length} onRetry={resource.retry}>
      <div className="portfolio-line"><div><span>Contract portfolio</span><strong>{data?.summary.portfolio?.totalContracts ?? contracts.length}<small>contracts</small></strong></div><div><span>Awaiting review</span><strong>{data?.summary.portfolio?.openReviews ?? reviews.filter(i => i.status !== 'Completed').length}<small>open items</small></strong></div><div><span>Compliance exceptions</span><strong className="exception-number">{data?.summary.portfolio?.complianceExceptions ?? counts.exception}<small>need attention</small></strong></div><Link to="/version-analysis" className="resume-review"><GitCompareArrows size={21} /><div><span>Continue reviewing</span><strong>{contracts.find(c => c.reviewStatus === 'Reviewing')?.name ?? contracts[0]?.name}</strong><small>Open version comparison</small></div><ArrowRight size={18} /></Link></div>
      <div className="workbench-columns"><section className="inbox-surface"><header className="section-title"><div><h2>Needs your attention</h2><p>Review the clause, resolve the issue, move it forward.</p></div><Link to="/review-queue">View queue <ArrowUpRight size={15} /></Link></header><div className="inbox-tabs" role="tablist" aria-label="Review filter">{['Open', 'Urgent', 'All'].map(name => <button key={name} role="tab" aria-selected={filter === name} className={filter === name ? 'selected' : ''} onClick={() => setFilter(name)}>{name}<span>{name === 'Open' ? reviews.filter(i => i.status !== 'Completed').length : name === 'Urgent' ? reviews.filter(i => i.priority === 'Urgent').length : reviews.length}</span></button>)}</div><div className="review-inbox">{tasks.map(item => <Link className="review-inbox-row" to={'/review-queue'} key={item.id}><div className={'review-file ' + (item.priority === 'Urgent' ? 'urgent-file' : '')}><FileText size={20} /></div><div className="review-inbox-copy"><div><strong>{item.contract}</strong><Badge>{item.priority}</Badge></div><p>{item.issue}</p><footer><span>{item.reviewer}</span><span>{item.due}</span></footer></div><ArrowUpRight className="row-arrow" size={18} /></Link>)}</div><footer className="inbox-footer"><ShieldCheck size={15} /><span>Review activity is persisted by the local API.</span></footer></section>
        <aside className="workbench-rail"><section className="rail-section"><header><h2>Portfolio health</h2><Link aria-label="Open compliance coverage" to="/compliance-coverage"><ArrowUpRight size={17} /></Link></header><div className="health-track" aria-label={`${counts.compliant} compliant, ${counts.review} need review, ${counts.exception} exceptions`}><span /><span /><span /></div>{[['Compliant', counts.compliant, 'healthy'], ['Needs review', counts.review, 'review'], ['Exception', counts.exception, 'exception']].map(([label, count, cls]) => <div className="health-row" key={label}><span><i className={String(cls)} />{label}</span><strong>{count}</strong></div>)}</section><section className="rail-section"><header><h2>Review team</h2><Link aria-label="Manage reviewer assignments" to="/reviewer-assignment"><ArrowUpRight size={17} /></Link></header>{reviewers.slice(0, 4).map(person => <div className="team-row" key={person.id}><span className="team-avatar">{person.name.split(' ').map(n => n[0]).join('')}</span><div><strong>{person.name}</strong><span>{person.role}</span></div><small>{person.assigned}<span>/{person.capacity}</span></small></div>)}</section><Link to="/clause-search" className="find-clause"><Search size={19} /><div><strong>Find a clause</strong><span>Search indexed agreements</span></div><ArrowRight size={16} /></Link></aside></div>
      <section className="recent-records"><header className="section-title"><div><h2>Recently updated contracts</h2><p>The latest versions in your register.</p></div><Link to="/contracts">All contracts <ArrowUpRight size={15} /></Link></header><div className="table-scroll"><table><thead><tr><th>Contract</th><th>Owner</th><th>Version</th><th>Compliance</th><th>Modified</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{contracts.slice(0, 4).map(contract => <tr key={contract.id}><td><Link className="record-name" to={`/contracts/${contract.id}`}><FileText size={17} /><span><strong>{contract.name}</strong><small>{contract.id}</small></span></Link></td><td>{contract.owner}</td><td>{contract.currentVersion}</td><td><Badge>{contract.compliance}</Badge></td><td>{contract.lastModified}</td><td><Link aria-label={`Open ${contract.name}`} to={`/contracts/${contract.id}`}><ArrowUpRight size={17} /></Link></td></tr>)}</tbody></table></div></section>
    </AsyncState></div>
}
