import { ArrowRight, BriefcaseBusiness, CircleHelp, UserCheck, UsersRound } from 'lucide-react'
import { useState } from 'react'
import { api, listFrom } from '../api/client'
import { useResource } from '../api/useResource'
import { AsyncState, Badge, Button, MetricCard, PageHeader, Panel, Progress } from '../components/ui'
import type { Assignment, Contract, Reviewer } from '../types/domain'

const workload = (reviewer: Reviewer) => reviewer.currentWorkload ?? reviewer.assigned ?? 0
const capacity = (reviewer: Reviewer) => reviewer.maxCapacity ?? reviewer.capacity ?? 0

export function ReviewerAssignmentPage() {
  const resource = useResource(async (signal) => { const [reviewersPayload, contractsPayload, assignmentsPayload] = await Promise.all([api.get<unknown>('/reviewers?page=1&pageSize=100', signal), api.get<unknown>('/contracts?page=1&pageSize=100', signal), api.get<unknown>('/reviewer-assignments?page=1&pageSize=100', signal)]); return { reviewers: listFrom<Reviewer>(reviewersPayload, 'reviewers'), contracts: listFrom<Contract>(contractsPayload, 'contracts'), confirmed: listFrom<Assignment>(assignmentsPayload, 'assignments') } }, [])
  const reviewers = resource.data?.reviewers ?? []; const confirmedIds = new Set((resource.data?.confirmed ?? []).map(item => item.contractId)); const waiting = (resource.data?.contracts ?? []).filter(c => c.reviewStatus !== 'Approved' && !confirmedIds.has(c.id))
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [mapping, setMapping] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState<Error>()
  const propose = async () => { setBusy(true); setError(undefined); setMessage(''); try { const payload = await api.post<unknown>('/reviewer-assignments/propose', { contractIds: waiting.map(c => c.id) }); const proposed = listFrom<Assignment>(payload, 'assignments', 'proposals'); setAssignments(proposed); setMapping(Object.fromEntries(proposed.map(item => [item.contractId, item.reviewerId]))) } catch (reason) { setError(reason instanceof Error ? reason : new Error('Unable to propose assignments')) } finally { setBusy(false) } }
  const confirm = async () => { setBusy(true); setError(undefined); setMessage(''); try { await api.post('/reviewer-assignments/confirm', { assignments: assignments.map(item => ({ contractId: item.contractId, reviewerId: mapping[item.contractId] ?? item.reviewerId, cost: item.cost ?? 0, confidence: mapping[item.contractId] === item.reviewerId ? item.confidence : 'Good fit' })) }); setMessage('Assignments confirmed and persisted.'); setAssignments([]); setMapping({}); await resource.reload() } catch (reason) { setError(reason instanceof Error ? reason : new Error('Unable to confirm assignments')) } finally { setBusy(false) } }
  const rows = assignments.map(a => ({ ...a, contract: waiting.find(c => c.id === a.contractId), reviewer: reviewers.find(r => r.id === mapping[a.contractId]) }))
  return <><PageHeader title="Reviewer Assignment" description="Maximize valid assignments, then minimize workload/expertise cost." actions={<><Button variant="secondary" onClick={propose} disabled={busy || !waiting.length}>{busy ? 'Working…' : 'Generate proposal'}</Button><Button onClick={confirm} disabled={busy || !assignments.length}><UserCheck size={16} /> Confirm assignments</Button></>} />
    <AsyncState loading={resource.loading} error={resource.error} empty={!reviewers.length} onRetry={resource.retry}>{message && <div className="toast" role="status"><span className="toast-check">✓</span>{message}</div>}{error && <div className="state-view state-error" role="alert"><p>{error.message}</p><Button variant="secondary" onClick={propose}>Try again</Button></div>}<div className="metrics-grid compact"><MetricCard label="Awaiting review" value={waiting.length} detail="Contracts eligible for assignment" tone="red" /><MetricCard label="Available reviewers" value={reviewers.filter(r => workload(r) < capacity(r)).length} detail={`${reviewers.reduce((sum, r) => sum + Math.max(0, capacity(r) - workload(r)), 0)} open capacity`} tone="green" /><MetricCard label="Proposed assignments" value={assignments.length} detail="Valid flow assignments" /><MetricCard label="Unassigned" value={Math.max(0, waiting.length - assignments.length)} detail="Needs manual review" tone="amber" /></div>
      <Panel title="Proposed assignment map" description="Min-cost max-flow output" className="assignment-map-panel"><div className="assignment-head"><span><BriefcaseBusiness size={16} />Contracts</span><span><UsersRound size={16} />Reviewers</span></div>{rows.length ? <div className="assignment-map">{rows.map(({ contractId, contract, reviewer, confidence }) => reviewer && <div className="assignment-row" key={contractId}><article><div><strong>{contractId}</strong><Badge>{contract?.risk ?? 'Medium'}</Badge></div><h3>{contract?.name ?? contractId}</h3><p>{contract?.type ?? 'Contract review'}</p></article><div className="assignment-link"><span /><ArrowRight /></div><article className="reviewer-compact"><div className="avatar">{reviewer.name.split(' ').map(s => s[0]).join('')}</div><div><select aria-label={`Reviewer for ${contractId}`} value={reviewer.id} onChange={e => setMapping(current => ({ ...current, [contractId]: e.target.value }))}>{reviewers.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><p>{reviewer.role} · {confidence}</p><Progress value={workload(reviewer)} max={capacity(reviewer)} label={`${workload(reviewer)}/${capacity(reviewer)} assigned`} /></div></article></div>)}</div> : <p className="muted">Generate a proposal to compute assignments.</p>}<div className="info-callout"><CircleHelp size={17} /><p>The flow solver maximizes valid assignments before minimizing workload and expertise cost.</p></div></Panel>
      <div className="reviewer-grid">{reviewers.map(reviewer => <article key={reviewer.id}><div className="reviewer-top"><div className="avatar">{reviewer.name.split(' ').map(s => s[0]).join('')}</div><div><h3>{reviewer.name}</h3><p>{reviewer.role}</p></div><Badge tone={capacity(reviewer) - workload(reviewer) > 2 ? 'available' : 'near-capacity'}>{capacity(reviewer) - workload(reviewer)} available</Badge></div><Progress value={workload(reviewer)} max={capacity(reviewer)} label={`${workload(reviewer)} assigned of ${capacity(reviewer)}`} /><footer>{reviewer.expertise?.map(item => <span key={item}>{item}</span>)}</footer></article>)}</div>
    </AsyncState></>
}
