import { Bell, Check, Eye, SlidersHorizontal, UserRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api, valueFrom } from '../api/client'
import { useResource } from '../api/useResource'
import { AsyncState, Button, PageHeader, Panel, Select } from '../components/ui'
import type { Settings } from '../types/domain'

const sections = [{ id: 'profile', label: 'Profile', icon: UserRound }, { id: 'review', label: 'Review preferences', icon: SlidersHorizontal }, { id: 'notifications', label: 'Notifications', icon: Bell }, { id: 'display', label: 'Display', icon: Eye }]
const defaults: Settings = { displayName: '', role: '', email: '', defaultQueueSort: 'Priority, then due date', versionComparison: 'Side-by-side', showClauseComplianceTags: true, confirmStatusChanges: true, newAssignments: true, dueDateReminders: true, complianceExceptions: true, weeklySummary: false }

export function SettingsPage() {
  const resource = useResource((signal) => api.get<unknown>('/settings', signal).then(p => ({ ...defaults, ...valueFrom<Partial<Settings>>(p, 'settings') })), [])
  const [settings, setSettings] = useState<Settings>(); const [section, setSection] = useState('profile'); const [density, setDensity] = useState(() => localStorage.getItem('display-density') ?? 'comfortable'); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [saveError, setSaveError] = useState<Error>()
  useEffect(() => { document.documentElement.dataset.density = density; localStorage.setItem('display-density', density) }, [density])
  const currentSettings = settings ?? resource.data ?? defaults
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(current => ({ ...(current ?? resource.data ?? defaults), [key]: value }))
  const save = async () => { setSaving(true); setSaved(false); setSaveError(undefined); try { const payload = await api.put<unknown>('/settings', currentSettings); setSettings({ ...defaults, ...valueFrom<Settings>(payload, 'settings') }); setSaved(true); window.setTimeout(() => setSaved(false), 2200) } catch (reason) { setSaveError(reason instanceof Error ? reason : new Error('Unable to save settings')) } finally { setSaving(false) } }
  return <><PageHeader title="Settings" description="Manage persisted workspace preferences and browser-only display density." /><AsyncState loading={resource.loading} error={resource.error} onRetry={resource.retry}><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{sections.map(({ id, label, icon: Icon }) => <button key={id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}><Icon size={17} />{label}</button>)}</nav><Panel className="settings-panel">
      {section === 'profile' && <SettingsSection title="Profile" copy="Your persisted review identity."><div className="profile-editor"><div className="avatar large">{currentSettings.displayName.split(' ').map(n => n[0]).join('').slice(0, 2) || 'CR'}</div><div><strong>{currentSettings.displayName || 'Compliance Reviewer'}</strong><span>{currentSettings.role || 'Review Team'}</span></div></div><div className="form-grid"><label><span>Display name</span><input value={currentSettings.displayName} onChange={e => update('displayName', e.target.value)} /></label><label><span>Role</span><input value={currentSettings.role} onChange={e => update('role', e.target.value)} /></label><label className="full"><span>Email address</span><input type="email" value={currentSettings.email} onChange={e => update('email', e.target.value)} /></label></div></SettingsSection>}
      {section === 'review' && <SettingsSection title="Review preferences" copy="Choose how contract review information is presented."><div className="form-grid"><Select label="Default queue sort" value={currentSettings.defaultQueueSort} onChange={e => update('defaultQueueSort', e.target.value)}><option>Priority, then due date</option><option>Due date</option><option>Recently updated</option></Select><Select label="Version comparison" value={currentSettings.versionComparison} onChange={e => update('versionComparison', e.target.value as Settings['versionComparison'])}><option>Side-by-side</option><option>Unified diff</option></Select><Toggle label="Show clause compliance tags" copy="Display compliance labels beside clauses." checked={currentSettings.showClauseComplianceTags} onChange={value => update('showClauseComplianceTags', value)} /><Toggle label="Confirm status changes" copy="Ask before completing a queue item." checked={currentSettings.confirmStatusChanges} onChange={value => update('confirmStatusChanges', value)} /></div></SettingsSection>}
      {section === 'notifications' && <SettingsSection title="Notifications" copy="Control which workspace events appear in the notification centre."><div className="toggle-list"><Toggle label="New assignments" copy="A contract is assigned to you." checked={currentSettings.newAssignments} onChange={v => update('newAssignments', v)} /><Toggle label="Due-date reminders" copy="A review is due within 48 hours." checked={currentSettings.dueDateReminders} onChange={v => update('dueDateReminders', v)} /><Toggle label="Compliance exceptions" copy="A contract receives an exception status." checked={currentSettings.complianceExceptions} onChange={v => update('complianceExceptions', v)} /><Toggle label="Weekly summary" copy="Receive a weekly workspace digest." checked={currentSettings.weeklySummary} onChange={v => update('weeklySummary', v)} /></div></SettingsSection>}
      {section === 'display' && <SettingsSection title="Display density" copy="This preference intentionally stays in this browser."><div className="density-options"><button className={density === 'comfortable' ? 'active' : ''} onClick={() => setDensity('comfortable')}><i className="density-comfortable" /><strong>Comfortable</strong><span>More space between rows</span></button><button className={density === 'compact' ? 'active' : ''} onClick={() => setDensity('compact')}><i className="density-compact" /><strong>Compact</strong><span>More information on screen</span></button></div></SettingsSection>}
      {saveError && <p className="form-error" role="alert">{saveError.message}</p>}<div className="settings-footer"><span>{saved && <><Check size={16} />Saved to the local API</>}</span><Button onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save changes'}</Button></div>
    </Panel></div></AsyncState></>
}

function SettingsSection({ title, copy, children }: { title: string; copy: string; children: React.ReactNode }) { return <div className="settings-section"><h2>{title}</h2><p>{copy}</p>{children}</div> }
function Toggle({ label, copy, checked, onChange }: { label: string; copy: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="toggle-row"><span><strong>{label}</strong><small>{copy}</small></span><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /><i /></label> }
