import { ArrowRight, GitCompareArrows, History, Info } from 'lucide-react'
import { useState } from 'react'
import { api, isMissingRoute, listFrom, valueFrom } from '../api/client'
import { useResource } from '../api/useResource'
import { AsyncState, Badge, Button, PageHeader, Panel, Select } from '../components/ui'
import type { ClauseChange, Contract, ContractVersion, VersionComparison } from '../types/domain'

const EMPTY_VERSIONS: ContractVersion[] = []

export function VersionAnalysisPage() {
  const contractsResource = useResource((signal) => api.get<unknown>('/contracts?page=1&pageSize=100', signal).then(p => listFrom<Contract>(p, 'contracts')), [])
  const [contractId, setContractId] = useState(''); const [baseVersion, setBaseVersion] = useState(''); const [comparedVersion, setComparedVersion] = useState(''); const [comparison, setComparison] = useState<VersionComparison>(); const [selectedId, setSelectedId] = useState(''); const [working, setWorking] = useState(false); const [mutationError, setMutationError] = useState<Error>()
  const effectiveContractId = contractId || contractsResource.data?.[0]?.id || ''
  const versionsResource = useResource((signal) => effectiveContractId ? api.get<Contract & { versions?: ContractVersion[] }>(`/contracts/${encodeURIComponent(effectiveContractId)}`, signal).then(p => p.versions ?? []) : Promise.resolve([]), [effectiveContractId])
  const versions = versionsResource.data ?? EMPTY_VERSIONS
  const effectiveBaseVersion = baseVersion || versions.at(-1)?.id || ''
  const effectiveComparedVersion = comparedVersion || versions[0]?.id || ''
  const compare = async () => { if (!effectiveContractId || !effectiveBaseVersion || !effectiveComparedVersion) return; setWorking(true); setMutationError(undefined); try { let payload: unknown; try { payload = await api.post<unknown>('/version-comparisons', { contractId: effectiveContractId, baseVersionId: effectiveBaseVersion, targetVersionId: effectiveComparedVersion }) } catch (error) { if (!isMissingRoute(error)) throw error; payload = await api.get<unknown>(`/contracts/${encodeURIComponent(effectiveContractId)}/compare?baseVersionId=${encodeURIComponent(effectiveBaseVersion)}&targetVersionId=${encodeURIComponent(effectiveComparedVersion)}`) } const result = valueFrom<VersionComparison>(payload, 'comparison'); const raw = result.changes ?? listFrom<ClauseChange>(payload, 'changes', 'clauseChanges'); const changes = raw.map((change, index) => ({ ...change, id: change.id ?? `CHANGE-${index + 1}`, clauseId: change.clauseId ?? (change as ClauseChange & { clauseKey?: string }).clauseKey ?? 'Clause', title: change.title ?? (change as ClauseChange & { clauseKey?: string }).clauseKey ?? 'Clause change' })); setComparison({ ...result, changes }); setSelectedId(changes[0]?.id ?? '') } catch (error) { setMutationError(error instanceof Error ? error : new Error('Comparison failed')) } finally { setWorking(false) } }
  const changes = comparison?.changes ?? []; const active = changes.find(c => c.id === selectedId) ?? changes[0]; const counts = { added: changes.filter(c => c.kind === 'Added').length, removed: changes.filter(c => c.kind === 'Removed').length, modified: changes.filter(c => c.kind === 'Modified').length }; const label = (id: string) => versions.find(v => v.id === id)?.label ?? id
  return <><PageHeader eyebrow="Document comparison" title="Version analysis" description="Align clause sequences and inspect word-level changes." actions={<Button variant="secondary" disabled={!effectiveContractId}><History size={16} /> {versions.length} versions</Button>} /><AsyncState loading={contractsResource.loading || versionsResource.loading} error={contractsResource.error ?? versionsResource.error} empty={!contractsResource.data?.length} onRetry={() => { contractsResource.retry(); versionsResource.retry() }}><Panel className="selector-panel"><div className="comparison-selectors"><Select label="Contract" value={effectiveContractId} onChange={e => { setContractId(e.target.value); setBaseVersion(''); setComparedVersion(''); setComparison(undefined) }}>{contractsResource.data?.map(c => <option key={c.id} value={c.id}>{c.name} / {c.id}</option>)}</Select><Select label="Base version" value={effectiveBaseVersion} onChange={e => setBaseVersion(e.target.value)}>{versions.map(v => <option key={v.id} value={v.id}>{v.label} / {v.date}</option>)}</Select><ArrowRight className="selector-arrow" /><Select label="Compared version" value={effectiveComparedVersion} onChange={e => setComparedVersion(e.target.value)}>{versions.map(v => <option key={v.id} value={v.id}>{v.label} / {v.date}</option>)}</Select><Button onClick={compare} disabled={working || !effectiveBaseVersion || effectiveBaseVersion === effectiveComparedVersion}><GitCompareArrows size={16} /> {working ? 'Comparing…' : 'Compare'}</Button></div><p className="demo-disclaimer"><Info size={15} />Clause alignment and word-level LCS are computed by the backend.</p>{mutationError && <p className="form-error" role="alert">{mutationError.message}</p>}</Panel>
      {comparison && <><div className="version-summary"><div><strong>{changes.length}</strong><span>Changes detected</span></div><div className="change-added"><strong>{comparison.added ?? counts.added}</strong><span>Added</span></div><div className="change-removed"><strong>{comparison.removed ?? counts.removed}</strong><span>Removed</span></div><div className="change-modified"><strong>{comparison.modified ?? counts.modified}</strong><span>Modified</span></div></div>{active ? <div className="diff-layout"><Panel title="Document comparison" description={`${effectiveContractId} / clause view`} className="diff-panel"><div className="diff-head"><div><span>Base</span><strong>{label(effectiveBaseVersion)}</strong></div><div><span>Current</span><strong>{label(effectiveComparedVersion)}</strong></div></div><div className="diff-body"><article><div className="document-folio">{label(effectiveBaseVersion)}</div><div className="clause-label"><span>{active.clauseId}</span><Badge>{active.kind}</Badge></div><h3>{active.title}</h3>{active.before ? <p className={active.kind === 'Removed' || active.kind === 'Modified' ? 'removed-line' : ''}>{active.before}</p> : <p className="empty-diff">Clause not present in this version.</p>}</article><article><div className="document-folio">{label(effectiveComparedVersion)}</div><div className="clause-label"><span>{active.clauseId}</span><Badge>{active.kind}</Badge></div><h3>{active.title}</h3>{active.after ? <p className={active.kind === 'Added' ? 'added-line' : active.kind === 'Modified' ? 'modified-line' : ''}>{active.after}</p> : <p className="empty-diff">Clause removed from this version.</p>}</article></div></Panel><Panel title="Detected changes" description="Select a clause alignment" className="change-review-panel"><div className="change-list">{changes.map(change => <button className={active.id === change.id ? 'active' : ''} key={change.id} onClick={() => setSelectedId(change.id)}><span>{change.id}</span><strong>{change.clauseId}</strong><small>{change.title}</small><Badge>{change.kind}</Badge></button>)}</div></Panel></div> : <Panel><p className="muted">No clause changes were detected.</p></Panel>}</>}
    </AsyncState></>
}
