import { Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { api } from '../../api/client'
import { Button } from '../../components/ui'

interface DraftClause { title: string; text: string }

export function VersionEditor({ contractId, onSaved, onCancel }: { contractId: string; onSaved: () => void; onCancel: () => void }) {
  const [label, setLabel] = useState(''); const [effectiveDate, setEffectiveDate] = useState(''); const [author, setAuthor] = useState(''); const [note, setNote] = useState(''); const [clauses, setClauses] = useState<DraftClause[]>([{ title: '', text: '' }]); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const updateClause = (index: number, key: keyof DraftClause, value: string) => setClauses((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item))
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await api.post(`/contracts/${contractId}/versions`, { label, effectiveDate, author, note, clauses: clauses.map((item) => ({ ...item, status: 'Needs Review', tier: 'Acceptable', guidance: '', sourceSection: item.title })) }); onSaved() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create version') } finally { setSaving(false) } }
  return <form className="dialog-form" onSubmit={submit}><div className="form-grid"><label><span>Version label</span><input required value={label} onChange={(e) => setLabel(e.target.value)} placeholder="v2.0" /></label><label><span>Effective date</span><input required type="date" value={effectiveDate} onChange={(e) => setEffectiveDate(e.target.value)} /></label><label><span>Author</span><input required minLength={2} value={author} onChange={(e) => setAuthor(e.target.value)} /></label><label><span>Version note</span><input value={note} onChange={(e) => setNote(e.target.value)} /></label></div><div className="clause-drafts"><div><strong>Clauses</strong><Button type="button" variant="quiet" onClick={() => setClauses((current) => [...current, { title: '', text: '' }])}><Plus size={13} /> Add clause</Button></div>{clauses.map((clause, index) => <fieldset key={index}><legend>Clause {index + 1}</legend><label><span>Title</span><input required minLength={2} value={clause.title} onChange={(e) => updateClause(index, 'title', e.target.value)} /></label><label><span>Text</span><textarea required rows={4} value={clause.text} onChange={(e) => updateClause(index, 'text', e.target.value)} /></label>{clauses.length > 1 && <Button type="button" variant="quiet" onClick={() => setClauses((current) => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={13} /> Remove</Button>}</fieldset>)}</div>{error && <p className="form-error" role="alert">{error}</p>}<footer className="dialog-actions"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Creating…' : 'Create version'}</Button></footer></form>
}
